# Generated by Django 4.0.6 on 2022-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hvs',
            name='student_age',
            field=models.PositiveIntegerField(),
        ),
    ]
